sudo: required
dist: public
language: node_js
node_js:
  - "7"
install:
  - npm install
script:
  - gulp build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN
  on:
    branch: master